package:
  name: boost
  version: 1.63.0

source:
  fn:  boost_1_63_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.bz2

build:
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]
  number: 0

requirements:
  build:
    - python

about:
  home: http://www.boost.org/
  license: Boost-1.0

