package:
  name: rdflib
  version: "4.2.1"

source:
  fn: rdflib-4.2.1.tar.gz
  url: https://pypi.python.org/packages/9d/fa/4198e8d8b444a4ace5c8fd86d128c2faa210a6e281973c8e5e16d978eaf4/rdflib-4.2.1.tar.gz
  md5: 528adaa10536d14a608507d7831711f5
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rdflib = rdflib:main
    #
    # Would create an entry point called rdflib that calls rdflib.main()

    - rdfpipe = rdflib.tools.rdfpipe:main
    - csv2rdf = rdflib.tools.csv2rdf:main
    - rdf2dot = rdflib.tools.rdf2dot:main
    - rdfs2dot = rdflib.tools.rdfs2dot:main
    - rdfgraphisomorphism = rdflib.tools.graphisomorphism:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python
    - isodate

test:
  # Python imports
  imports:
    - rdflib

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/RDFLib/rdflib
  license: BSD License
  summary: 'RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
