#ifndef AbstractImmersedBoundaryDivisionRule3_hpp__pyplusplus_wrapper
#define AbstractImmersedBoundaryDivisionRule3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractImmersedBoundaryDivisionRule3_class(py::module &m);
#endif // AbstractImmersedBoundaryDivisionRule3_hpp__pyplusplus_wrapper
