#ifndef AbstractCaSwitchingUpdateRule2_hpp__pyplusplus_wrapper
#define AbstractCaSwitchingUpdateRule2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractCaSwitchingUpdateRule2_class(py::module &m);
#endif // AbstractCaSwitchingUpdateRule2_hpp__pyplusplus_wrapper
