#ifndef AbstractCellPopulationWriter2_2_hpp__pyplusplus_wrapper
#define AbstractCellPopulationWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractCellPopulationWriter2_2_class(py::module &m);
#endif // AbstractCellPopulationWriter2_2_hpp__pyplusplus_wrapper
