#ifndef AbstractImmersedBoundaryForce2_hpp__pyplusplus_wrapper
#define AbstractImmersedBoundaryForce2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractImmersedBoundaryForce2_class(py::module &m);
#endif // AbstractImmersedBoundaryForce2_hpp__pyplusplus_wrapper
