#ifndef AbstractCentreBasedDivisionRule3_3_hpp__pyplusplus_wrapper
#define AbstractCentreBasedDivisionRule3_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractCentreBasedDivisionRule3_3_class(py::module &m);
#endif // AbstractCentreBasedDivisionRule3_3_hpp__pyplusplus_wrapper
