#ifndef AbstractCellPopulationCountWriter2_2_hpp__pyplusplus_wrapper
#define AbstractCellPopulationCountWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractCellPopulationCountWriter2_2_class(py::module &m);
#endif // AbstractCellPopulationCountWriter2_2_hpp__pyplusplus_wrapper
