#ifndef AbstractCentreBasedDivisionRule2_2_hpp__pyplusplus_wrapper
#define AbstractCentreBasedDivisionRule2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractCentreBasedDivisionRule2_2_class(py::module &m);
#endif // AbstractCentreBasedDivisionRule2_2_hpp__pyplusplus_wrapper
