#ifndef AbstractCellPopulationEventWriter2_2_hpp__pyplusplus_wrapper
#define AbstractCellPopulationEventWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractCellPopulationEventWriter2_2_class(py::module &m);
#endif // AbstractCellPopulationEventWriter2_2_hpp__pyplusplus_wrapper
