#ifndef BiasedBernoulliTrialCellCycleModel_hpp__pyplusplus_wrapper
#define BiasedBernoulliTrialCellCycleModel_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_BiasedBernoulliTrialCellCycleModel_class(py::module &m);
#endif // BiasedBernoulliTrialCellCycleModel_hpp__pyplusplus_wrapper
