#ifndef CellsGeneratorTysonNovakCellCycleModel_3_hpp__pyplusplus_wrapper
#define CellsGeneratorTysonNovakCellCycleModel_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorTysonNovakCellCycleModel_3_class(py::module &m);
#endif // CellsGeneratorTysonNovakCellCycleModel_3_hpp__pyplusplus_wrapper
