#ifndef CellProliferativeTypesWriter3_3_hpp__pyplusplus_wrapper
#define CellProliferativeTypesWriter3_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellProliferativeTypesWriter3_3_class(py::module &m);
#endif // CellProliferativeTypesWriter3_3_hpp__pyplusplus_wrapper
