#ifndef CellDivisionLocationsWriter2_2_hpp__pyplusplus_wrapper
#define CellDivisionLocationsWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellDivisionLocationsWriter2_2_class(py::module &m);
#endif // CellDivisionLocationsWriter2_2_hpp__pyplusplus_wrapper
