#ifndef CellsGeneratorExponentialG1GenerationalCellCycleModel_3_hpp__pyplusplus_wrapper
#define CellsGeneratorExponentialG1GenerationalCellCycleModel_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorExponentialG1GenerationalCellCycleModel_3_class(py::module &m);
#endif // CellsGeneratorExponentialG1GenerationalCellCycleModel_3_hpp__pyplusplus_wrapper
