#ifndef CellPopulationAdjacencyMatrixWriter2_2_hpp__pyplusplus_wrapper
#define CellPopulationAdjacencyMatrixWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellPopulationAdjacencyMatrixWriter2_2_class(py::module &m);
#endif // CellPopulationAdjacencyMatrixWriter2_2_hpp__pyplusplus_wrapper
