#ifndef CellsGeneratorGammaG1CellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorGammaG1CellCycleModel_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorGammaG1CellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorGammaG1CellCycleModel_2_hpp__pyplusplus_wrapper
