#ifndef CellsGeneratorAlwaysDivideCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorAlwaysDivideCellCycleModel_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorAlwaysDivideCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorAlwaysDivideCellCycleModel_2_hpp__pyplusplus_wrapper
