#ifndef CellsGeneratorAlarcon2004OxygenBasedCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorAlarcon2004OxygenBasedCellCycleModel_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorAlarcon2004OxygenBasedCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorAlarcon2004OxygenBasedCellCycleModel_2_hpp__pyplusplus_wrapper
