#ifndef CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_3_hpp__pyplusplus_wrapper
#define CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_3_class(py::module &m);
#endif // CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_3_hpp__pyplusplus_wrapper
