#ifndef CellProliferativeTypesCountWriter2_2_hpp__pyplusplus_wrapper
#define CellProliferativeTypesCountWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellProliferativeTypesCountWriter2_2_class(py::module &m);
#endif // CellProliferativeTypesCountWriter2_2_hpp__pyplusplus_wrapper
