#ifndef CellsGeneratorBernoulliTrialCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorBernoulliTrialCellCycleModel_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorBernoulliTrialCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorBernoulliTrialCellCycleModel_2_hpp__pyplusplus_wrapper
