#ifndef CellsGeneratorStochasticOxygenBasedCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorStochasticOxygenBasedCellCycleModel_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorStochasticOxygenBasedCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorStochasticOxygenBasedCellCycleModel_2_hpp__pyplusplus_wrapper
