#ifndef CellsGeneratorBiasedBernoulliTrialCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorBiasedBernoulliTrialCellCycleModel_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorBiasedBernoulliTrialCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorBiasedBernoulliTrialCellCycleModel_2_hpp__pyplusplus_wrapper
