#ifndef CellsGeneratorFixedG1GenerationalCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorFixedG1GenerationalCellCycleModel_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorFixedG1GenerationalCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorFixedG1GenerationalCellCycleModel_2_hpp__pyplusplus_wrapper
