#ifndef CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_2_hpp__pyplusplus_wrapper
