#ifndef CellsGeneratorBernoulliTrialCellCycleModel_3_hpp__pyplusplus_wrapper
#define CellsGeneratorBernoulliTrialCellCycleModel_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorBernoulliTrialCellCycleModel_3_class(py::module &m);
#endif // CellsGeneratorBernoulliTrialCellCycleModel_3_hpp__pyplusplus_wrapper
