#ifndef CellCycleModelProteinConcentrationsWriter3_3_hpp__pyplusplus_wrapper
#define CellCycleModelProteinConcentrationsWriter3_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellCycleModelProteinConcentrationsWriter3_3_class(py::module &m);
#endif // CellCycleModelProteinConcentrationsWriter3_3_hpp__pyplusplus_wrapper
