#ifndef CellProliferativeTypesWriter2_2_hpp__pyplusplus_wrapper
#define CellProliferativeTypesWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellProliferativeTypesWriter2_2_class(py::module &m);
#endif // CellProliferativeTypesWriter2_2_hpp__pyplusplus_wrapper
