#ifndef CellsGeneratorFixedSequenceCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorFixedSequenceCellCycleModel_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellsGeneratorFixedSequenceCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorFixedSequenceCellCycleModel_2_hpp__pyplusplus_wrapper
