#ifndef CellPopulationElementWriter2_2_hpp__pyplusplus_wrapper
#define CellPopulationElementWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellPopulationElementWriter2_2_class(py::module &m);
#endif // CellPopulationElementWriter2_2_hpp__pyplusplus_wrapper
