#ifndef CellRemovalLocationsWriter2_2_hpp__pyplusplus_wrapper
#define CellRemovalLocationsWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellRemovalLocationsWriter2_2_class(py::module &m);
#endif // CellRemovalLocationsWriter2_2_hpp__pyplusplus_wrapper
