#ifndef CellMutationStatesCountWriter2_2_hpp__pyplusplus_wrapper
#define CellMutationStatesCountWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellMutationStatesCountWriter2_2_class(py::module &m);
#endif // CellMutationStatesCountWriter2_2_hpp__pyplusplus_wrapper
