#ifndef CellProliferativePhasesWriter2_2_hpp__pyplusplus_wrapper
#define CellProliferativePhasesWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CellProliferativePhasesWriter2_2_class(py::module &m);
#endif // CellProliferativePhasesWriter2_2_hpp__pyplusplus_wrapper
