#ifndef DeltaNotchEdgeInteriorTrackingModifier2_hpp__pyplusplus_wrapper
#define DeltaNotchEdgeInteriorTrackingModifier2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_DeltaNotchEdgeInteriorTrackingModifier2_class(py::module &m);
#endif // DeltaNotchEdgeInteriorTrackingModifier2_hpp__pyplusplus_wrapper
