#ifndef DivisionBiasTrackingModifier3_hpp__pyplusplus_wrapper
#define DivisionBiasTrackingModifier3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_DivisionBiasTrackingModifier3_class(py::module &m);
#endif // DivisionBiasTrackingModifier3_hpp__pyplusplus_wrapper
