#ifndef EllipticBoxDomainPdeModifier2_hpp__pyplusplus_wrapper
#define EllipticBoxDomainPdeModifier2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_EllipticBoxDomainPdeModifier2_class(py::module &m);
#endif // EllipticBoxDomainPdeModifier2_hpp__pyplusplus_wrapper
