#ifndef FixedVertexBasedDivisionRule2_hpp__pyplusplus_wrapper
#define FixedVertexBasedDivisionRule2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_FixedVertexBasedDivisionRule2_class(py::module &m);
#endif // FixedVertexBasedDivisionRule2_hpp__pyplusplus_wrapper
