#ifndef FixedCentreBasedDivisionRule2_2_hpp__pyplusplus_wrapper
#define FixedCentreBasedDivisionRule2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_FixedCentreBasedDivisionRule2_2_class(py::module &m);
#endif // FixedCentreBasedDivisionRule2_2_hpp__pyplusplus_wrapper
