#ifndef HeterotypicBoundaryLengthWriter3_3_hpp__pyplusplus_wrapper
#define HeterotypicBoundaryLengthWriter3_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_HeterotypicBoundaryLengthWriter3_3_class(py::module &m);
#endif // HeterotypicBoundaryLengthWriter3_3_hpp__pyplusplus_wrapper
