#ifndef ImmersedBoundaryLinearInteractionForce2_hpp__pyplusplus_wrapper
#define ImmersedBoundaryLinearInteractionForce2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ImmersedBoundaryLinearInteractionForce2_class(py::module &m);
#endif // ImmersedBoundaryLinearInteractionForce2_hpp__pyplusplus_wrapper
