#ifndef ImmersedBoundaryCellPopulation3_hpp__pyplusplus_wrapper
#define ImmersedBoundaryCellPopulation3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ImmersedBoundaryCellPopulation3_class(py::module &m);
#endif // ImmersedBoundaryCellPopulation3_hpp__pyplusplus_wrapper
