#ifndef ImmersedBoundaryLinearDifferentialAdhesionForce2_hpp__pyplusplus_wrapper
#define ImmersedBoundaryLinearDifferentialAdhesionForce2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ImmersedBoundaryLinearDifferentialAdhesionForce2_class(py::module &m);
#endif // ImmersedBoundaryLinearDifferentialAdhesionForce2_hpp__pyplusplus_wrapper
