#ifndef ImmersedBoundaryMorseMembraneForce2_hpp__pyplusplus_wrapper
#define ImmersedBoundaryMorseMembraneForce2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ImmersedBoundaryMorseMembraneForce2_class(py::module &m);
#endif // ImmersedBoundaryMorseMembraneForce2_hpp__pyplusplus_wrapper
