#ifndef ImmersedBoundaryCellPopulation2_hpp__pyplusplus_wrapper
#define ImmersedBoundaryCellPopulation2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ImmersedBoundaryCellPopulation2_class(py::module &m);
#endif // ImmersedBoundaryCellPopulation2_hpp__pyplusplus_wrapper
