#ifndef ImmersedBoundaryBoundaryCellWriter3_3_hpp__pyplusplus_wrapper
#define ImmersedBoundaryBoundaryCellWriter3_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ImmersedBoundaryBoundaryCellWriter3_3_class(py::module &m);
#endif // ImmersedBoundaryBoundaryCellWriter3_3_hpp__pyplusplus_wrapper
