#ifndef ImmersedBoundaryNeighbourNumberWriter2_2_hpp__pyplusplus_wrapper
#define ImmersedBoundaryNeighbourNumberWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ImmersedBoundaryNeighbourNumberWriter2_2_class(py::module &m);
#endif // ImmersedBoundaryNeighbourNumberWriter2_2_hpp__pyplusplus_wrapper
