#ifndef ImmersedBoundarySimulationModifier2_hpp__pyplusplus_wrapper
#define ImmersedBoundarySimulationModifier2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ImmersedBoundarySimulationModifier2_class(py::module &m);
#endif // ImmersedBoundarySimulationModifier2_hpp__pyplusplus_wrapper
