#ifndef ImmersedBoundaryBoundaryCellWriter2_2_hpp__pyplusplus_wrapper
#define ImmersedBoundaryBoundaryCellWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ImmersedBoundaryBoundaryCellWriter2_2_class(py::module &m);
#endif // ImmersedBoundaryBoundaryCellWriter2_2_hpp__pyplusplus_wrapper
