#ifndef LabelDependentBernoulliTrialCellCycleModel_hpp__pyplusplus_wrapper
#define LabelDependentBernoulliTrialCellCycleModel_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_LabelDependentBernoulliTrialCellCycleModel_class(py::module &m);
#endif // LabelDependentBernoulliTrialCellCycleModel_hpp__pyplusplus_wrapper
