#ifndef LegacyCellProliferativeTypesWriter2_2_hpp__pyplusplus_wrapper
#define LegacyCellProliferativeTypesWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_LegacyCellProliferativeTypesWriter2_2_class(py::module &m);
#endif // LegacyCellProliferativeTypesWriter2_2_hpp__pyplusplus_wrapper
