#ifndef NodeBasedCellPopulationWithBuskeUpdate2_hpp__pyplusplus_wrapper
#define NodeBasedCellPopulationWithBuskeUpdate2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_NodeBasedCellPopulationWithBuskeUpdate2_class(py::module &m);
#endif // NodeBasedCellPopulationWithBuskeUpdate2_hpp__pyplusplus_wrapper
