#ifndef PlanarPolarisedFarhadifarForce3_hpp__pyplusplus_wrapper
#define PlanarPolarisedFarhadifarForce3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_PlanarPolarisedFarhadifarForce3_class(py::module &m);
#endif // PlanarPolarisedFarhadifarForce3_hpp__pyplusplus_wrapper
