#ifndef PlanarPolarisedFarhadifarForce2_hpp__pyplusplus_wrapper
#define PlanarPolarisedFarhadifarForce2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_PlanarPolarisedFarhadifarForce2_class(py::module &m);
#endif // PlanarPolarisedFarhadifarForce2_hpp__pyplusplus_wrapper
