#ifndef RadialCellDataDistributionWriter2_2_hpp__pyplusplus_wrapper
#define RadialCellDataDistributionWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_RadialCellDataDistributionWriter2_2_class(py::module &m);
#endif // RadialCellDataDistributionWriter2_2_hpp__pyplusplus_wrapper
