#ifndef ShortAxisVertexBasedDivisionRule3_hpp__pyplusplus_wrapper
#define ShortAxisVertexBasedDivisionRule3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ShortAxisVertexBasedDivisionRule3_class(py::module &m);
#endif // ShortAxisVertexBasedDivisionRule3_hpp__pyplusplus_wrapper
