#ifndef ShortAxisImmersedBoundaryDivisionRule2_hpp__pyplusplus_wrapper
#define ShortAxisImmersedBoundaryDivisionRule2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ShortAxisImmersedBoundaryDivisionRule2_class(py::module &m);
#endif // ShortAxisImmersedBoundaryDivisionRule2_hpp__pyplusplus_wrapper
