#ifndef ShortAxisVertexBasedDivisionRule2_hpp__pyplusplus_wrapper
#define ShortAxisVertexBasedDivisionRule2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ShortAxisVertexBasedDivisionRule2_class(py::module &m);
#endif // ShortAxisVertexBasedDivisionRule2_hpp__pyplusplus_wrapper
