#ifndef TargetAreaLinearGrowthModifier2_hpp__pyplusplus_wrapper
#define TargetAreaLinearGrowthModifier2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_TargetAreaLinearGrowthModifier2_class(py::module &m);
#endif // TargetAreaLinearGrowthModifier2_hpp__pyplusplus_wrapper
