#ifndef VertexT1SwapLocationsWriter2_2_hpp__pyplusplus_wrapper
#define VertexT1SwapLocationsWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_VertexT1SwapLocationsWriter2_2_class(py::module &m);
#endif // VertexT1SwapLocationsWriter2_2_hpp__pyplusplus_wrapper
