#ifndef VertexT2SwapLocationsWriter3_3_hpp__pyplusplus_wrapper
#define VertexT2SwapLocationsWriter3_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_VertexT2SwapLocationsWriter3_3_class(py::module &m);
#endif // VertexT2SwapLocationsWriter3_3_hpp__pyplusplus_wrapper
