#ifndef VertexIntersectionSwapLocationsWriter2_2_hpp__pyplusplus_wrapper
#define VertexIntersectionSwapLocationsWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_VertexIntersectionSwapLocationsWriter2_2_class(py::module &m);
#endif // VertexIntersectionSwapLocationsWriter2_2_hpp__pyplusplus_wrapper
