#ifndef VertexT3SwapLocationsWriter2_2_hpp__pyplusplus_wrapper
#define VertexT3SwapLocationsWriter2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_VertexT3SwapLocationsWriter2_2_class(py::module &m);
#endif // VertexT3SwapLocationsWriter2_2_hpp__pyplusplus_wrapper
