#ifndef VertexT3SwapLocationsWriter3_3_hpp__pyplusplus_wrapper
#define VertexT3SwapLocationsWriter3_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_VertexT3SwapLocationsWriter3_3_class(py::module &m);
#endif // VertexT3SwapLocationsWriter3_3_hpp__pyplusplus_wrapper
