#ifndef VonMisesVertexBasedDivisionRule3_hpp__pyplusplus_wrapper
#define VonMisesVertexBasedDivisionRule3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_VonMisesVertexBasedDivisionRule3_class(py::module &m);
#endif // VonMisesVertexBasedDivisionRule3_hpp__pyplusplus_wrapper
