#ifndef VonMisesVertexBasedDivisionRule2_hpp__pyplusplus_wrapper
#define VonMisesVertexBasedDivisionRule2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_VonMisesVertexBasedDivisionRule2_class(py::module &m);
#endif // VonMisesVertexBasedDivisionRule2_hpp__pyplusplus_wrapper
