package:
  name: swig
  version: 3.0.7

source:
  fn: swig-3.0.7.tar.gz
  url: http://prdownloads.sourceforge.net/swig/swig-3.0.7.tar.gz
  md5: 7fff46c84b8c630ede5b0f0827e3d90a

build:
  detect_binary_files_with_prefix: True

requirements:
  build:
#    - gcc
    - zlib
    - pcre
    - python

  run:
#    - libgcc
    - zlib
    - pcre

test:
  commands:
    - swig -help

about:
    home: http://www.swig.org/
    license: GPLv3
