{% set build = 1 %}
{% set version = '3.7.4' %}
{% set md5 = '5e6fd3c047c4a087d6deecc9a6a77743' %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=1.10'} %}

package:
  name: petsc
  version: {{version}}

source:
  fn: petsc-lite-{{version}}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{version}}.tar.gz
  md5: {{md5}}

build:
  number: {{build}}
  binary_relocation: true
  detect_binary_files_with_prefix: true
  skip: true  # [win or py3k]
  features:
    - blas_{{blas}}

requirements:
  build:
    - python
    - cmake
    - blas 1.* {{blas}}
    - toolchain
    - {{mpi}} {{req[mpi]}}
  run:
    - blas 1.* {{blas}}
    - {{mpi}} {{req[mpi]}}

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
