{% set build = 0 %}
{% set version = '3.7.5' %}
{% set md5 = 'bfc7a5535d5c18c6ec81ab90f3ce5074' %}

package:
  name: petsc
  version: {{version}}

source:
  fn: petsc-lite-{{version}}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{version}}.tar.gz
  md5: {{md5}}

build:
  number: 0
  binary_relocation: true
  detect_binary_files_with_prefix: true
  skip: true  # [win or py3k]

requirements:
  build:
    - python
    - cmake
    - readline

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE
