{% set version = "3.4.4" %}
{% set build = 0 %}

{% set build_string = "py{}h{}_{}".format(CONDA_PY, PKG_HASH, build) %}

package:
  name: chaste
  version: {{ version }}

source:
  path: /tmp/Chaste

build:
  number: {{ build }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - python
    - git
    - {{ cdt('libsm-devel') }}
    - {{ cdt('libxext') }}

  host:
    - python
    - boost-cpp >=1.68, <1.76
    - hdf5 >=1.10, <1.11
    - hdf5 * mpi_mpich*
    - metis >=4
    - mpich 4.0.*
    - parmetis >=4
    - petsc >=3.12, <3.17
    - petsc4py
    - sundials >=3.0,<6.0
    - vtk 7.1.1
    - xerces-c >=3
    - xsd 4.*

  run:
    - python
    - boost-cpp >=1.68, <1.76
    - hdf5 >=1.10, <1.11
    - hdf5 * mpi_mpich*
    - metis >=4
    - mpich 4.0.*
    - parmetis >=4
    - petsc >=3.12, <3.17
    - petsc4py
    - sundials >=3.0,<6.0
    - vtk 7.1.1
    - xerces-c >=3
    - xsd 4.*
    - matplotlib
    - numpy

test:
  imports:
    - chaste

about:
  home: http://www.cs.ox.ac.uk/chaste/
  license: BSD-3-Clause
  summary: >
    Chaste is a general purpose simulation package for computational biology.
  dev_url: https://github.com/Chaste/Chaste
  doc_url: https://chaste.github.io
