package:
  name: fiat
  version: "1.6.0"

source:
  fn: fiat-1.6.0.tar.gz
  url: https://bitbucket.org/fenics-project/fiat/downloads/fiat-1.6.0.tar.gz
  md5: f4509d05c911fd93cea8d288a78a6c6f

build:
  number: 1

requirements:
  build:
    - python
    - sympy

  run:
    - python
    - numpy
    - sympy

test:
  imports:
    - FIAT

  requires:
    - nose

about:
  home: http://fenicsproject.org/
  license: The GNU Lesser General Public License, version 3.0
  summary: 'FInite element Automatic Tabulator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
