#ifndef ImmersedBoundaryPalisadeMeshGenerator_hpp__pyplusplus_wrapper
#define ImmersedBoundaryPalisadeMeshGenerator_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ImmersedBoundaryPalisadeMeshGenerator_class(py::module &m);
#endif // ImmersedBoundaryPalisadeMeshGenerator_hpp__pyplusplus_wrapper
