#ifndef ToroidalHoneycombVertexMeshGenerator_hpp__pyplusplus_wrapper
#define ToroidalHoneycombVertexMeshGenerator_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_ToroidalHoneycombVertexMeshGenerator_class(py::module &m);
#endif // ToroidalHoneycombVertexMeshGenerator_hpp__pyplusplus_wrapper
