package:
  name: vtk
  version: 7.1.1

source:
  fn:  VTK-7.1.1.tar.gz
  url: http://www.vtk.org/files/release/7.1/VTK-7.1.1.tar.gz


build:
  number: 4
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python
    - cmake >=3.6
    - petsc # mpi libs

  run:
    - python
    - petsc

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.
