package:
  name: vtk
  version: "7.0.0"

source:
  url: http://www.vtk.org/files/release/7.0/VTK-7.0.0.tar.gz
  fn:  VTK-7.0.0.tar.gz

build:
  number: 6
  features:
    - vc9                [win and py27]
    - vc10               [win and py34]
    - vc14               [win and py35]

requirements:
  build:
    - gcc # [linux and (py27 or py34 or py35)]
    - mesa # [linux and (py27 or py34 or py35)]
    - cmake
    - python
  run:
    - mesa # [linux and (py27 or py34 or py35)]
    - libgcc # [linux and (py27 or py34 or py35)]
    - python

test:
  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets

about:
  home: http://www.vtk.org/
  license: BSD
  summary: VTK is an open-source, freely available software system for 3D computer graphics
