#ifndef AbstractNonlinearEllipticPde1_hpp__pyplusplus_wrapper
#define AbstractNonlinearEllipticPde1_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractNonlinearEllipticPde1_class(py::module &m);
#endif // AbstractNonlinearEllipticPde1_hpp__pyplusplus_wrapper
