name: pychaste-docker

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      meta-images: |
        chaste/pychaste
      meta-flavor: latest=true
      meta-tags: |
        type=raw,value=latest
      labels: |
        org.opencontainers.image.title=PyChaste Docker Image
        org.opencontainers.image.description=PyChaste: Python Bindings for Chaste
        org.opencontainers.image.url=https://hub.docker.com/repository/docker/chaste/pychaste
        org.opencontainers.image.source=https://github.com/Chaste/PyChaste
        org.opencontainers.image.documentation=https://chaste.github.io/pychaste/
      context: ./infra/docker/
      file: Dockerfile
      platforms: linux/amd64,linux/arm64
      output: image
      push: true
      distribute: true
      sign: auto
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
